### ISSUE TITLE
DB Connection pool exhaust with SQLAlchemy/PostgreSQL

### ISSUE THREAD

**Issue by justb4** [geopython/GeoHealthCheck#140]
Observed only when running GHC with PostgreSQL backend, here with `gunicorn` in Docker env. After some time of activity GHC gives a 500 failure. The log shows: 

```
geohealthcheck_1              | [2017-07-17 07:26:08,450] ERROR in app: Exception on / [GET]
geohealthcheck_1              | Traceback (most recent call last):
geohealthcheck_1              |   File "/venv/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
geohealthcheck_1              |     response = self.full_dispatch_request()
geohealthcheck_1              |   File "/venv/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
geohealthcheck_1              |     rv = self.handle_user_exception(e)
geohealthcheck_1              |   File "/venv/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
geohealthcheck_1              |     reraise(exc_type, exc_value, tb)
geohealthcheck_1              |   File "/venv/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
geohealthcheck_1              |     rv = self.dispatch_request()
geohealthcheck_1              |   File "/venv/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
geohealthcheck_1              |     return self.view_functions[rule.endpoint](**req.view_args)
geohealthcheck_1              |   File "/GeoHealthCheck/GeoHealthCheck/app.py", line 220, in home
geohealthcheck_1              |     response = views.list_resources(resource_type, query, tag)
geohealthcheck_1              |   File "/GeoHealthCheck/GeoHealthCheck/views.py", line 60, in list_resources
geohealthcheck_1              |     resource_type=resource_type).all()
geohealthcheck_1              |   File "/venv/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2703, in all
geohealthcheck_1              |     return list(self)
geohealthcheck_1              |   File "/venv/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2855, in __iter__
geohealthcheck_1              |     return self._execute_and_instances(context)
geohealthcheck_1              |   File "/venv/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2876, in _execute_and_instances
geohealthcheck_1              |     close_with_result=True)
geohealthcheck_1              |   File "/venv/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2885, in _get_bind_args
geohealthcheck_1              |     **kw
geohealthcheck_1              |   File "/venv/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2867, in _connection_from_session
geohealthcheck_1              |     conn = self.session.connection(**kw)
geohealthcheck_1              |   File "/venv/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 998, in connection
geohealthcheck_1              |     execution_options=execution_options)
geohealthcheck_1              |   File "/venv/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 1003, in _connection_for_bind
geohealthcheck_1              |     engine, execution_options)
geohealthcheck_1              |   File "/venv/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 403, in _connection_for_bind
geohealthcheck_1              |     conn = bind.contextual_connect()
geohealthcheck_1              |   File "/venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 2112, in contextual_connect
geohealthcheck_1              |     self._wrap_pool_connect(self.pool.connect, None),
geohealthcheck_1              |   File "/venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 2147, in _wrap_pool_connect
geohealthcheck_1              |     return fn()
geohealthcheck_1              |   File "/venv/lib/python2.7/site-packages/sqlalchemy/pool.py", line 387, in connect
geohealthcheck_1              |     return _ConnectionFairy._checkout(self)
geohealthcheck_1              |   File "/venv/lib/python2.7/site-packages/sqlalchemy/pool.py", line 766, in _checkout
geohealthcheck_1              |     fairy = _ConnectionRecord.checkout(pool)
geohealthcheck_1              |   File "/venv/lib/python2.7/site-packages/sqlalchemy/pool.py", line 516, in checkout
geohealthcheck_1              |     rec = pool._do_get()
geohealthcheck_1              |   File "/venv/lib/python2.7/site-packages/sqlalchemy/pool.py", line 1131, in _do_get
geohealthcheck_1              |     (self.size(), self.overflow(), self._timeout))
geohealthcheck_1              | TimeoutError: QueuePool limit of size 5 overflow 10 reached, connection timed out, timeout 30
```
Looks like a PG connection-pool exhaust. Could be due by improper `SQLAlchemy` `Session` mgt, in particular not freeing resources, possibly `Session.close()` needs to be called after commits. Looks a lot like [this problem](https://stackoverflow.com/questions/3360951/sql-alchemy-connection-time-out).

**Comment by justb4** [comment]
The latter commit also got rid of this error from `Postgresql`, due to GHC Check Runner exit without removing connections: 

```
postgis_ghc_1                 | LOG:  unexpected EOF on client connection with an open transaction
```

**Comment by justb4** [comment]
Solved, tested in all envs: Docker, PG, SQlite etc.
