### ISSUE TITLE
Docker-compose running issue

### ISSUE THREAD

**Issue by StephanZaat** [geopython/GeoHealthCheck#152]
Hi, 

The project looks great! I'm interested in running this for our open geoservices and APIs at data.amsterdam.nl. 
I'm trying to start the default docker-compose but when opening localhost:8083 I see this in the logs.

```
geohealthcheck_1              | [2017-08-02 07:26:05,529] ERROR in app: Exception on / [GET]
geohealthcheck_1              | Traceback (most recent call last):
geohealthcheck_1              |   File "/venv/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
geohealthcheck_1              |     response = self.full_dispatch_request()
geohealthcheck_1              |   File "/venv/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
geohealthcheck_1              |     rv = self.handle_user_exception(e)
geohealthcheck_1              |   File "/venv/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
geohealthcheck_1              |     reraise(exc_type, exc_value, tb)
geohealthcheck_1              |   File "/venv/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
geohealthcheck_1              |     rv = self.dispatch_request()
geohealthcheck_1              |   File "/venv/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
geohealthcheck_1              |     return self.view_functions[rule.endpoint](**req.view_args)
geohealthcheck_1              |   File "/GeoHealthCheck/GeoHealthCheck/app.py", line 216, in home
geohealthcheck_1              |     response = views.get_health_summary()
geohealthcheck_1              |   File "/GeoHealthCheck/GeoHealthCheck/views.py", line 132, in get_health_summary
geohealthcheck_1              |     last_runs = models.get_last_runs(total_resources)
geohealthcheck_1              |   File "/GeoHealthCheck/GeoHealthCheck/models.py", line 396, in get_last_runs
geohealthcheck_1              |     Run.identifier > (last_id - rsc_count)).limit(count).all()
geohealthcheck_1              | TypeError: unsupported operand type(s) for -: 'NoneType' and 'long'

```
When I enter the docker and run the paver upgrade I also get an error:

```
(venv) bash-4.3# paver upgrade
---> pavement.upgrade
Upgrading database...
cd /GeoHealthCheck/GeoHealthCheck
python manage.py db upgrade
Traceback (most recent call last):
  File "manage.py", line 42, in <module>
    from init import DB, APP
ImportError: cannot import name DB


Captured Task Output:
---------------------

---> pavement.upgrade
Upgrading database...
cd /GeoHealthCheck/GeoHealthCheck
python manage.py db upgrade

Build failed running pavement.upgrade: Subprocess return code: 1
```
Before I start digging deeper I wanted to check if I'm missing something obvious here.

Regards,
Stephan

**Comment by justb4** [comment]
I see that the error is occurs  in very recently (yesterday) added code with PR #151. I run GHC also with Docker, but with an existing database. Think the error occurs when the DB history table `Run` is empty (no runs)...testing locally, yes, I get same stacktrace. For a fresh install you don't need `paver upgrade`, this may be another problem.

So fix upcoming. One thing you could try for now is to login, add a Resource and doing at least one or more runs via commandline, i.e. when `bash` into GHC main container:

```
cd /GeoHealthCheck/GeoHealthCheck
python models.py run
```
and open `localhost:8083` again.

**Comment by justb4** [comment]
Should be fixed and available in Docker images, `latest` and `dev`. Can you remove the GHC containers/images and try again?

**Comment by StephanZaat** [comment]
@justb4 Works like a charm! Thanks!
