### ISSUE TITLE
Error EVENT_JOB_MISSED

### ISSUE THREAD

**Issue by dersteppenwolf** [geopython/GeoHealthCheck#288]
From time to time the following error appears on runner:
(looks like the scheduler doesn't work after that)

`
2019-10-05 13:07:09,734 - __main__ - ERROR - error_listener: EVENT_JOB_MISSED - <JobExecutionEvent (code=8192)>
2019-10-05 13:12:09,730 - apscheduler.executors.default - ERROR - Job "check_schedule (trigger: interval[0:05:00], next run at: 2019-10-05 13:17:09 BST)" raised an exception
Traceback (most recent call last):
  File "/venv/lib/python2.7/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "GeoHealthCheck/scheduler.py", line 198, in check_schedule
    for resource in Resource.query.all():
  File "/venv/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 3167, in all
    return list(self)
  File "/venv/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 3323, in __iter__
    return self._execute_and_instances(context)
  File "/venv/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 3348, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 988, in execute
    return meth(self, multiparams, params)
  File "/venv/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 287, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1107, in _execute_clauseelement
    distilled_params,
  File "/venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1182, in _execute_context
    e, util.text_type(statement), parameters, None, None
  File "/venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1466, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "/venv/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 383, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1177, in _execute_context
    conn = self._revalidate_connection()
  File "/venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 463, in _revalidate_connection
    "Can't reconnect until invalid "
StatementError: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
[SQL: SELECT resource.auth AS resource_auth, resource.identifier AS resource_identifier, resource.resource_type AS resource_resource_type, resource.active AS resource_active, resource.title AS resource_title, resource.url AS resource_url, resource.latitude AS resource_latitude, resource.longitude AS resource_longitude, resource.owner_identifier AS resource_owner_identifier, resource.run_frequency AS resource_run_frequency
FROM resource]
[parameters: [{}]]
2019-10-05 13:12:09,731 - __main__ - ERROR - error_listener: EVENT_JOB_MISSED - <JobExecutionEvent (code=8192)>
`

Enviroment: docker 
BD: Postgresql

**Comment by justb4** [comment]
This looks like a database connection problem. At least I have never seen this error in any of the production instances of GHC (demo site and several others). The `apscheduler`, seems quite stable. Is the error consistent? Also if you restart. In any case you need to provide some more context details:

- GHC Docker version, or built your own
* Postgres (Docker image) version
* OS+version

We need to be able to reproduce the error otherwise it will be hard to debug.

**Comment by dersteppenwolf** [comment]
Looks like a similar error is affecting ghc_web


```
[2019-10-07 16:49:19,895] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "/venv/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/venv/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/venv/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/venv/lib/python2.7/site-packages/flask/app.py", line 1610, in full_dispatch_request
    rv = self.preprocess_request()
  File "/venv/lib/python2.7/site-packages/flask/app.py", line 1831, in preprocess_request
    rv = func()
  File "/GeoHealthCheck/GeoHealthCheck/app.py", line 113, in before_request
    g.user.is_authenticated(),  # This is from Flask-Login
  File "/venv/lib/python2.7/site-packages/werkzeug/local.py", line 348, in __getattr__
    return getattr(self._get_current_object(), name)
  File "/venv/lib/python2.7/site-packages/werkzeug/local.py", line 307, in _get_current_object
    return self.__local()
  File "/venv/lib/python2.7/site-packages/flask_login.py", line 46, in <lambda>
    current_user = LocalProxy(lambda: _get_user())
  File "/venv/lib/python2.7/site-packages/flask_login.py", line 794, in _get_user
    current_app.login_manager._load_user()
  File "/venv/lib/python2.7/site-packages/flask_login.py", line 363, in _load_user
    return self.reload_user()
  File "/venv/lib/python2.7/site-packages/flask_login.py", line 325, in reload_user
    user = self.user_callback(user_id)
  File "/GeoHealthCheck/GeoHealthCheck/app.py", line 142, in load_user
    return User.query.get(int(identifier))
  File "/venv/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 959, in get
    return self._get_impl(ident, loading.load_on_pk_identity)
  File "/venv/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 1069, in _get_impl
    return db_load_fn(self, primary_key_identity)
  File "/venv/lib/python2.7/site-packages/sqlalchemy/orm/loading.py", line 282, in load_on_pk_identity
    return q.one()
  File "/venv/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 3281, in one
    ret = self.one_or_none()
  File "/venv/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 3250, in one_or_none
    ret = list(self)
  File "/venv/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 3323, in __iter__
    return self._execute_and_instances(context)
  File "/venv/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 3348, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 988, in execute
    return meth(self, multiparams, params)
  File "/venv/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 287, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1107, in _execute_clauseelement
    distilled_params,
  File "/venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1248, in _execute_context
    e, statement, parameters, cursor, context
  File "/venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1466, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "/venv/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 383, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1244, in _execute_context
    cursor, statement, parameters, context
  File "/venv/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 550, in do_execute
    cursor.execute(statement, parameters)
DatabaseError: (psycopg2.DatabaseError) SSL SYSCALL error: Operation timed out

[SQL: SELECT "user".user_id AS user_user_id, "user".username AS user_username, "user".password AS user_password, "user".email AS user_email, "user".role AS user_role, "user".registered_on AS user_registered_on
FROM "user"
WHERE "user".user_id = %(param_1)s]
[parameters: {'param_1': 1}]
(Background on this error at: http://sqlalche.me/e/4xp6)
```


**Enviroment:**

**GHC Docker version:**  
built our own from master due to https://github.com/geopython/GeoHealthCheck/pull/281

**Postgres version:**  
"PostgreSQL 11.3 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-36), 64-bit"
DB Standalone

**OS+version:** 
Operating System: CentOS Linux 7 (Core)
  Kernel: Linux 3.10.0-1062.1.1.el7.x86_64
  Architecture: x86-64

**Comment by dersteppenwolf** [comment]
Looks like the problem is caused by a network policy regarding timeouts of database connections in production servers.

It seems that currently DB connections are open for a _"very long time"_ and the server blocks them causing GeoHealthCheck to fail (web / Runner).  

I added some other flask-sqlalchemy parameters but it isn't working:

```
sudo docker run -d  --restart always \
    -e GHC_RUNNER_IN_WEBAPP=False \
    -e ADMIN_NAME=user\
    -e ADMIN_PWD=pwd\
    -e ADMIN_EMAIL=email@example.com \
    -e GHC_SITE_URL=http://myserver/geohealthcheck/ \
    -e GHC_ADMIN_EMAIL=email@example.com \
    -e GHC_REQUIRE_WEBAPP_AUTH=True \
    -e GHC_RETENTION_DAYS=90 \
    -e GHC_SELF_REGISTER=False \
    -e SCRIPT_NAME=/geohealthcheck \
    -e GHC_NOTIFICATIONS=True \
	-e GHC_NOTIFICATIONS_VERBOSITY=True \
    -e GHC_SITE_TITLE='GeoHealthCheck' \
    -e GHC_NOTIFICATIONS_EMAIL='email@example.com' \
    -e GHC_SMTP_SERVER=smtp.gmail.com \
	-e GHC_SMTP_PORT=587 \
	-e GHC_SMTP_TLS=True \
	-e GHC_SMTP_SSL=False \
	-e GHC_SMTP_USERNAME=email@example.com \
	-e GHC_SMTP_PASSWORD=pwd\
    -e SQLALCHEMY_DATABASE_URI=postgresql://dbuser:dbpwd@dbserver:5432/geohealthcheck \
    -e SQLALCHEMY_ENGINE_OPTIONS='isolation_level=AUTOCOMMIT,pool_timeout=30,pool_recycle=180,pool_size=5'  \
    --name ghc_web  \
     -p 5004:80  my/geohealthcheck:latest
```

**Comment by dersteppenwolf** [comment]
Finally the problem was caused by an incorrect configuration given by the DBA to the following system parameters:

"tcp_keepalives_count"
"tcp_keepalives_idle"
"tcp_keepalives_interval"

It wasn't a problem of GeoHealthCheck.
