### ISSUE TITLE
Differences between config_site.py and config_main.py

### ISSUE THREAD

**Issue by fsteggink** [geopython/GeoHealthCheck#370]
Hi, I've noticed a couple of differences between the files docker/config_site.py and GeoHealthCheck/config_main.py. The latter is containing the variables SQLALCHEMY_TRACK_MODIFICATIONS, GHC_METADATA_CACHE_SECS and GHC_PROBE_DEFAULTS, which are missing in the former. It might be a good idea to add them to the Docker config as well.

As an additional note, config_main.py is using arrays for the variables GHC_PLUGINS and GHC_USER_PLUGINS, but when reading them as env. vars in config_site.py, the values will be strings. That doesn't seem correct to me.

**Comment by justb4** [comment]
GHC config eventually a combination of `GeoHealthCheck/a, `instance/config_site.py` and an optional `GHC_SETTINGS` var (which can be a file path). Config values are overridden in that order, so if e.g. a value is not present in `config_site.py`, it is taken from `config_main.py`. See also the [documentation](https://docs.geohealthcheck.org/en/latest/config.html) and the [init.py code](https://github.com/geopython/GeoHealthCheck/blob/master/GeoHealthCheck/init.py#L69).
One reason is to enable a minimal configuration with plenty of defaults. 
But yes for completeness may specify all.

`GHC_PLUGINS` and `GHC_USER_PLUGINS`: any format: comma-separated string, `list` `set` can be specified. The [init.py code](https://github.com/geopython/GeoHealthCheck/blob/master/GeoHealthCheck/init.py#L85) will resolve this. Also historic reasons: Docker and ENV vars came in later in the project.

**Comment by fsteggink** [comment]
Yes, I've read about the various configuration options, and eventually figured out that by specifying a custom file through GHC_SETTINGS I can also override things like probe defaults. However I have no idea if the missing variables in config_site.py (docker) is on purpose or not. I see no reason not to specify GHC_METADATA_CACHE_SECS through an env file for Docker.

Regarding GHC_PLUGINS / GHC_USER_PLUGINS, the documentation currently says the following:
```
GHC_PLUGINS: list of Core/built-in Plugin classes or modules available on installation

GHC_USER_PLUGINS: list of Plugin classes or modules provided by user (you)
```
It is not obvious that this should be a comma separated string.

**Comment by fsteggink** [comment]
Another thing that surprised me (and I didn't try to find the cause of it yet) is that the file docker/compose/ghc.env doesn't try to specify all different config variables. Yet, docker/config_site.py uses os.environ['VARNAME'] all over the place, instead of os.environ.get('VARNAME'), and it doesn't seem that GHC has any problems with it. GHC starts properly, and in the logging I don't see any possible errors related to missing env vars or KeyErrors like in this example:
```
>>> import os
>>> os.environ['GHC_DOESNOTEXIST']
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Apps\Python37\lib\os.py", line 681, in __getitem__
    raise KeyError(key) from None
KeyError: 'GHC_DOESNOTEXIST'
```

**Comment by justb4** [comment]
Forgot to add this (was in Gitter):  
*Correction: ENV defaults are set in the Dockerfile, so when not specified during deployment, those values are taken, hence os.environ.get('NAME', default) was not required.*

**Comment by fsteggink** [comment]
Yes, that's right. I didn't think about any env vars set in the Dockerfile (or by some other means in the Docker container).
