### ISSUE TITLE
[docker] Cron triggers an error

### ISSUE THREAD

**Issue by yjacolin** [geopython/GeoHealthCheck#41]
In my docker container, cron trigger such error:
```
Traceback (most recent call last):
  File "models.py", line 255, in <module>
    notify(APP.config, res, run1, last_run_success)
  File "/GeoHealthCheck/GeoHealthCheck/notifications.py", line 53, in notify
    result = gettext('Passing')
  File "/venv/local/lib/python2.7/site-packages/flask_babel/__init__.py", line 538, in gettext
    t = get_translations()
  File "/venv/local/lib/python2.7/site-packages/flask_babel/__init__.py", line 215, in get_translations
    babel = current_app.extensions['babel']
  File "/venv/local/lib/python2.7/site-packages/werkzeug/local.py", line 343, in __getattr__
    return getattr(self._get_current_object(), name)
  File "/venv/local/lib/python2.7/site-packages/werkzeug/local.py", line 302, in _get_current_object
    return self.__local()
  File "/venv/local/lib/python2.7/site-packages/flask/globals.py", line 34, in _find_app
    raise RuntimeError('working outside of application context')
RuntimeError: working outside of application context
```
Any idea why?

**Comment by hannesaddec** [comment]
Are you using virtualenv environment and activated it also for cron?

Mit TouchDown von meinem Android-Telefon gesendet (www.symantec.com)

-----Original Message-----

**Comment by yjacolin** [comment]
yes, I ran the same command line manually:
```
root@c9be7856df3c:/GeoHealthCheck/GeoHealthCheck# . /venv/bin/activate
(venv)root@c9be7856df3c:/GeoHealthCheck/GeoHealthCheck# python models.py run
[see error essage above]
```
It is something linked with docker container as it is working correctly when installing in the host server.
