### ISSUE TITLE
Paver setup fails on data_dir.chmod(0777)

### ISSUE THREAD

**Issue by justb4** [geopython/GeoHealthCheck#55]
Trying to install GHC master sept 13, 2016 on Ubuntu 14.04 with Paver 1.2.1, Python 2.7, I get this error message:

```
vagrant@vagrant-ubuntu-trusty-64:/var/www/ghc$ sudo paver setup
---> pavement.setup

mkdir /var/www/ghc/instance
mkdir /var/www/ghc/instance/data


Captured Task Output:
---------------------

---> pavement.setup
mkdir /var/www/ghc/instance
mkdir /var/www/ghc/instance/data
Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.7/paver/tasks.py", line 195, in _run_task
    return do_task()
  File "/usr/lib/pymodules/python2.7/paver/tasks.py", line 192, in do_task
    return func(**kw)
  File "pavement.py", line 71, in setup
    data_dir.chmod(0777)
  File "/usr/lib/pymodules/python2.7/paver/path.py", line 66, in wrapper
    msg = name + ' ' + ' '.join(args)
TypeError: sequence item 1: expected string, int found
```

The failure comes from ``/usr/lib/pymodules/python2.7/paver/path.py`` line 66, where``msg = name + ' ' + ' '.join(args)``   expects a string, not an int (0777). But when I change in pavement.py line 71 to ``data_dir.chmod('0777') `` I obviously get another error:

```
---> pavement.setup
mkdir /var/www/ghc/instance
mkdir /var/www/ghc/instance/data
chmod /var/www/ghc/instance/data 0777
Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.7/paver/tasks.py", line 195, in _run_task
    return do_task()
  File "/usr/lib/pymodules/python2.7/paver/tasks.py", line 192, in do_task
    return func(**kw)
  File "pavement.py", line 71, in setup
    data_dir.chmod('0777')
  File "/usr/lib/pymodules/python2.7/paver/path.py", line 69, in wrapper
    return dry(msg, func, *args, **kwds)
  File "/usr/lib/pymodules/python2.7/paver/easy.py", line 18, in dry
    return func(*args, **kw)
  File "/usr/lib/pymodules/python2.7/paver/deps/path2.py", line 924, in chmod
    os.chmod(self, mode)
TypeError: an integer is required
```
A second run of ``paver setup`` goes ok as the errored line is skipped (``instance`` dir exists). 
Commenting out the line ``data_dir.chmod(0777)`` gives no errors.

This may be due to my combination of Python & Paver versions? I will look further. But ``chmod()`` should be a normal function for Paver ``Bunch`` instances. As a last resort ``os.chmod()`` may be called directly but this defeats the purpose of Paver...

Any insights welcome!

**Comment by justb4** [comment]
Ok works. May close.
