### ISSUE TITLE
Upgrade to latest GHC Master Branch from existing system

### ISSUE THREAD

**Issue by samperd** [geopython/GeoHealthCheck#84]
Hey Folks,

I tried upgrading my existing GHC system to the latest master and have now run into some issues.

The general process I followed
* Ctrl+C to bring down service
* Backed up DB (365 days of history, don't want to loose it)
* Backed up config.py (guess it is called something else now)
* git pull (failed: complained of overwritting config.py, likely due to a rename function)
* git stash (since it complained about overwritting config.py)
* git pull (worked)
* python GeoHealthCheck/app.py (complained of some sqlalchamey errors)
* paver setup (to ensure other packages are updated and propper versions)
* pip install --upgrade pip (because paver complained of old pip)
* paver setup (to ensure all pip requirements are set)
* cp instance/config.py instance/config_site.py (GHC README now uses a new syntax for config I guess)
* vim instance/config_site.py (to ensure settings are still there)
* python GeoHealthCheck/app.py (fails with following trace. see below)

Is this because there needs to be a process to upgrade OLD DB's to new DB schema?

`Traceback (most recent call last)

    File "/home/sampsond/applications/GeoHealthCheck/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
    File "/home/sampsond/applications/GeoHealthCheck/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
    File "/home/sampsond/applications/GeoHealthCheck/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
    File "/home/sampsond/applications/GeoHealthCheck/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
    File "/home/sampsond/applications/GeoHealthCheck/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
    File "/home/sampsond/applications/GeoHealthCheck/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
    File "/home/sampsond/applications/GeoHealthCheck/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()

    File "/home/sampsond/applications/GeoHealthCheck/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request

    return self.view_functions[rule.endpoint](**req.view_args)

    File "/home/sampsond/applications/GeoHealthCheck/GeoHealthCheck/GeoHealthCheck/app.py", line 205, in home

    return render_template('home.html', response=response)

    File "/home/sampsond/applications/GeoHealthCheck/lib/python2.7/site-packages/flask/templating.py", line 126, in render_template

    ctx.app.update_template_context(context)

    File "/home/sampsond/applications/GeoHealthCheck/lib/python2.7/site-packages/flask/app.py", line 716, in update_template_context

    context.update(func())

    File "/home/sampsond/applications/GeoHealthCheck/GeoHealthCheck/GeoHealthCheck/app.py", line 178, in context_processors

    tags = views.get_tag_counts()

    File "/home/sampsond/applications/GeoHealthCheck/GeoHealthCheck/GeoHealthCheck/views.py", line 115, in get_tag_counts

    return models.get_tag_counts()

    File "/home/sampsond/applications/GeoHealthCheck/GeoHealthCheck/GeoHealthCheck/models.py", line 230, in get_tag_counts

    return dict(query)

    File "/home/sampsond/applications/GeoHealthCheck/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2516, in __iter__

    return self._execute_and_instances(context)

    File "/home/sampsond/applications/GeoHealthCheck/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2531, in _execute_and_instances

    result = conn.execute(querycontext.statement, self._params)

    File "/home/sampsond/applications/GeoHealthCheck/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 914, in execute

    return meth(self, multiparams, params)

    File "/home/sampsond/applications/GeoHealthCheck/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 323, in _execute_on_connection

    return connection._execute_clauseelement(self, multiparams, params)

    File "/home/sampsond/applications/GeoHealthCheck/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1010, in _execute_clauseelement

    compiled_sql, distilled_params

    File "/home/sampsond/applications/GeoHealthCheck/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1146, in _execute_context

    context)

    File "/home/sampsond/applications/GeoHealthCheck/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1341, in _handle_dbapi_exception

    exc_info

    File "/home/sampsond/applications/GeoHealthCheck/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 199, in raise_from_cause

    reraise(type(exception), exception, tb=exc_tb)

    File "/home/sampsond/applications/GeoHealthCheck/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1139, in _execute_context

    context)

    File "/home/sampsond/applications/GeoHealthCheck/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 450, in do_execute

    cursor.execute(statement, parameters)

    OperationalError: (sqlite3.OperationalError) no such table: resource_tags [SQL: u'SELECT tag.name AS tag_name, count(resource.identifier) AS count_1 \nFROM resource JOIN resource_tags AS resource_tags_1 ON resource.identifier = resource_tags_1.resource_identifier JOIN tag ON tag.id = resource_tags_1.tag_id GROUP BY tag.id']

The debugger caught an exception in your WSGI application. You can now look at the traceback which led to the error.

To switch between the interactive traceback and the plaintext one, you can click on the "Traceback" headline. From the text traceback you can also create a paste of it. For code execution mouse-over the frame you want to debug and click on the console icon on the right side.

You can execute arbitrary Python code in the stack frames and there are some extra helpers available for introspection:

    dump() shows all variables in the frame
    dump(obj) dumps all that's known about the object

`

**Comment by justb4** [comment]
See https://github.com/geopython/GeoHealthCheck/issues/75#issuecomment-278474934

Looking at your actions I noticed:

- `config.py`:  I am not aware of this file, only `instance/site_config.py` (which remained intact in my case)
- you don't call `paver create`, this will create the new tag-tables, leaving your existing tables intact (but a backup is recommended anyway)

But I had a more recent masterbranch version...You may need to compare/inspect your `config.py`.

**Comment by samperd** [comment]
`config.py` was an old GHC artifact I guess, so I copied it to the new `site_config.py` naming convention.

Running `paver create` worked. I was afraid it would overwrite the existing DB. perhaps we can update the README.md (https://github.com/geopython/GeoHealthCheck/blob/master/README.md) to read:

`# setup new database or update existing database and superuser account
paver create` 

Thanks for the suggestion to run `paver create`.
